# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'applylateclockin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApplyLateClockIn(object):
    def setupUi(self, ApplyLateClockIn):
        ApplyLateClockIn.setObjectName("ApplyLateClockIn")
        ApplyLateClockIn.resize(1070, 650)
        ApplyLateClockIn.setMinimumSize(QtCore.QSize(1070, 650))
        ApplyLateClockIn.setMaximumSize(QtCore.QSize(1070, 650))
        ApplyLateClockIn.setStyleSheet("QDialog\n"
"{\n"
"    background-color: rgb(234, 255, 185)\n"
"}")
        self.pushButton = QtWidgets.QPushButton(ApplyLateClockIn)
        self.pushButton.setGeometry(QtCore.QRect(830, 410, 210, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ApplyLateClockIn)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 485, 210, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(255, 170, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(230, 153, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(197, 128, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(ApplyLateClockIn)
        self.tableWidget.setGeometry(QtCore.QRect(3, 50, 1061, 331))
        self.tableWidget.setStyleSheet("QTableWidget::item:selected {\n"
"    background-color:#C1272D;\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.dateEdit_3 = QtWidgets.QDateEdit(ApplyLateClockIn)
        self.dateEdit_3.setGeometry(QtCore.QRect(50, 420, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(12)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setStyleSheet("QDateEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QDateEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QDateEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.dateEdit_3.setWrapping(False)
        self.dateEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_3.setDisplayFormat("dd/MM/yyyy")
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.label = QtWidgets.QLabel(ApplyLateClockIn)
        self.label.setGeometry(QtCore.QRect(50, 390, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ApplyLateClockIn)
        self.label_2.setGeometry(QtCore.QRect(50, 510, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ApplyLateClockIn)
        self.label_3.setGeometry(QtCore.QRect(320, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(ApplyLateClockIn)
        self.textEdit.setGeometry(QtCore.QRect(320, 420, 470, 180))
        self.textEdit.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(ApplyLateClockIn)
        self.pushButton_3.setGeometry(QtCore.QRect(830, 560, 210, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    font-size:13pt;\n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.timeEdit_2 = QtWidgets.QTimeEdit(ApplyLateClockIn)
        self.timeEdit_2.setGeometry(QtCore.QRect(50, 540, 240, 40))
        self.timeEdit_2.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_2.setAccelerated(True)
        self.timeEdit_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_2.setProperty("showGroupSeparator", True)
        self.timeEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_2.setDisplayFormat("hh:mm")
        self.timeEdit_2.setCalendarPopup(True)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(ApplyLateClockIn)
        self.dateEdit.setGeometry(QtCore.QRect(60, 6, 121, 30))
        self.dateEdit.setStyleSheet("QDateEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QDateEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QDateEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.dateEdit.setDisplayFormat("yyyy")
        self.dateEdit.setObjectName("dateEdit")
        self.label_29 = QtWidgets.QLabel(ApplyLateClockIn)
        self.label_29.setGeometry(QtCore.QRect(11, 1, 41, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_29.setObjectName("label_29")
        self.comboBox_3 = QtWidgets.QComboBox(ApplyLateClockIn)
        self.comboBox_3.setGeometry(QtCore.QRect(290, 6, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("QComboBox\n"
"\n"
"    {font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"\n"
"}\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_30 = QtWidgets.QLabel(ApplyLateClockIn)
        self.label_30.setGeometry(QtCore.QRect(220, 0, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_30.setObjectName("label_30")
        self.label_4 = QtWidgets.QLabel(ApplyLateClockIn)
        self.label_4.setGeometry(QtCore.QRect(440, 0, 420, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(ApplyLateClockIn)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApplyLateClockIn)

    def retranslateUi(self, ApplyLateClockIn):
        _translate = QtCore.QCoreApplication.translate
        ApplyLateClockIn.setWindowTitle(_translate("ApplyLateClockIn", "Apply Late Clock-In"))
        self.pushButton.setText(_translate("ApplyLateClockIn", "Send"))
        self.pushButton_2.setText(_translate("ApplyLateClockIn", "Withdraw"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplyLateClockIn", "Request ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplyLateClockIn", "Request DTTM"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplyLateClockIn", "Date of Late"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplyLateClockIn", "Clock-In Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ApplyLateClockIn", "Remarks"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ApplyLateClockIn", "Leader"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ApplyLateClockIn", "DM"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ApplyLateClockIn", "HR"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("ApplyLateClockIn", "Date of Late Clock-In"))
        self.label_2.setText(_translate("ApplyLateClockIn", "Clock-In Time"))
        self.label_3.setText(_translate("ApplyLateClockIn", "Remarks (Optional)"))
        self.pushButton_3.setText(_translate("ApplyLateClockIn", "Close"))
        self.label_29.setText(_translate("ApplyLateClockIn", "Year"))
        self.comboBox_3.setCurrentText(_translate("ApplyLateClockIn", "01"))
        self.comboBox_3.setItemText(0, _translate("ApplyLateClockIn", "01"))
        self.comboBox_3.setItemText(1, _translate("ApplyLateClockIn", "02"))
        self.comboBox_3.setItemText(2, _translate("ApplyLateClockIn", "03"))
        self.comboBox_3.setItemText(3, _translate("ApplyLateClockIn", "04"))
        self.comboBox_3.setItemText(4, _translate("ApplyLateClockIn", "05"))
        self.comboBox_3.setItemText(5, _translate("ApplyLateClockIn", "06"))
        self.comboBox_3.setItemText(6, _translate("ApplyLateClockIn", "07"))
        self.comboBox_3.setItemText(7, _translate("ApplyLateClockIn", "08"))
        self.comboBox_3.setItemText(8, _translate("ApplyLateClockIn", "09"))
        self.comboBox_3.setItemText(9, _translate("ApplyLateClockIn", "10"))
        self.comboBox_3.setItemText(10, _translate("ApplyLateClockIn", "11"))
        self.comboBox_3.setItemText(11, _translate("ApplyLateClockIn", "12"))
        self.comboBox_3.setItemText(12, _translate("ApplyLateClockIn", "All"))
        self.label_30.setText(_translate("ApplyLateClockIn", "Month"))
        self.label_4.setText(_translate("ApplyLateClockIn", "(Year & Month of Late Clock-In Days)"))
