# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'approve_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApprovePanel(object):
    def setupUi(self, ApprovePanel):
        ApprovePanel.setObjectName("ApprovePanel")
        ApprovePanel.resize(1296, 776)
        self.centralwidget = QtWidgets.QWidget(ApprovePanel)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 1281, 721))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget\n"
"{\n"
"    background-color: rgb(243, 247, 255)\n"
"\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(20, 0, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(20, 80, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_34.setObjectName("label_34")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_11.setEnabled(False)
        self.textEdit_11.setGeometry(QtCore.QRect(20, 30, 270, 50))
        self.textEdit_11.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_11.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_11.setLineWidth(1)
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_12.setEnabled(False)
        self.textEdit_12.setGeometry(QtCore.QRect(20, 110, 270, 50))
        self.textEdit_12.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_12.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_12.setLineWidth(1)
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(20, 240, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_35.setObjectName("label_35")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_13.setEnabled(False)
        self.textEdit_13.setGeometry(QtCore.QRect(20, 270, 270, 50))
        self.textEdit_13.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_13.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_13.setLineWidth(1)
        self.textEdit_13.setObjectName("textEdit_13")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(20, 320, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_36.setObjectName("label_36")
        self.textEdit_14 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_14.setEnabled(False)
        self.textEdit_14.setGeometry(QtCore.QRect(20, 350, 270, 50))
        self.textEdit_14.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_14.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_14.setLineWidth(1)
        self.textEdit_14.setObjectName("textEdit_14")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(20, 400, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_37.setObjectName("label_37")
        self.textEdit_15 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_15.setEnabled(False)
        self.textEdit_15.setGeometry(QtCore.QRect(20, 430, 270, 50))
        self.textEdit_15.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_15.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_15.setLineWidth(1)
        self.textEdit_15.setObjectName("textEdit_15")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(20, 480, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_38.setObjectName("label_38")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 510, 270, 170))
        self.textEdit_2.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(20, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_39.setObjectName("label_39")
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_16.setEnabled(False)
        self.textEdit_16.setGeometry(QtCore.QRect(20, 190, 270, 50))
        self.textEdit_16.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_16.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_16.setLineWidth(1)
        self.textEdit_16.setObjectName("textEdit_16")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(320, 0, 951, 611))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: rgb(225, 255, 254);\n"
"\n"
"}")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_3.setRowCount(1)
        self.tableWidget_3.setColumnCount(11)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 630, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(960, 630, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(320, 630, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(20, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(20, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(20, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_27.setObjectName("label_27")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setEnabled(False)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 430, 270, 50))
        self.textEdit_5.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_5.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_5.setLineWidth(1)
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(20, 480, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_28.setObjectName("label_28")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(20, 510, 270, 170))
        self.textEdit.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(640, 640, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setEnabled(False)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 190, 270, 50))
        self.textEdit_6.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_6.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_6.setLineWidth(1)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_7.setEnabled(False)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 270, 270, 50))
        self.textEdit_7.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_7.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_7.setLineWidth(1)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_8.setEnabled(False)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 350, 270, 50))
        self.textEdit_8.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_8.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_8.setLineWidth(1)
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(20, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_31.setObjectName("label_31")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_9.setEnabled(False)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 110, 270, 50))
        self.textEdit_9.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_9.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_9.setLineWidth(1)
        self.textEdit_9.setObjectName("textEdit_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(320, 0, 951, 631))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: rgb(225, 255, 254);\n"
"\n"
"}")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(930, 640, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(20, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_32.setObjectName("label_32")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_10.setEnabled(False)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 30, 270, 50))
        self.textEdit_10.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_10.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_10.setLineWidth(1)
        self.textEdit_10.setObjectName("textEdit_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 640, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        self.label_40.setGeometry(QtCore.QRect(20, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_40.setObjectName("label_40")
        self.textEdit_17 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_17.setEnabled(False)
        self.textEdit_17.setGeometry(QtCore.QRect(20, 30, 280, 50))
        self.textEdit_17.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_17.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_17.setLineWidth(1)
        self.textEdit_17.setObjectName("textEdit_17")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 350, 280, 330))
        self.textEdit_3.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(20, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_41.setObjectName("label_41")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(20, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_30.setObjectName("label_30")
        self.textEdit_18 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_18.setEnabled(False)
        self.textEdit_18.setGeometry(QtCore.QRect(20, 270, 280, 50))
        self.textEdit_18.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_18.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_18.setLineWidth(1)
        self.textEdit_18.setObjectName("textEdit_18")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(950, 630, 290, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_42.setObjectName("label_42")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 630, 290, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(20, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_44.setObjectName("label_44")
        self.textEdit_21 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_21.setEnabled(False)
        self.textEdit_21.setGeometry(QtCore.QRect(20, 110, 280, 50))
        self.textEdit_21.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_21.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_21.setLineWidth(1)
        self.textEdit_21.setObjectName("textEdit_21")
        self.textEdit_22 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_22.setEnabled(False)
        self.textEdit_22.setGeometry(QtCore.QRect(20, 190, 280, 50))
        self.textEdit_22.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_22.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_22.setLineWidth(1)
        self.textEdit_22.setObjectName("textEdit_22")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(319, 0, 951, 611))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: rgb(225, 255, 254);\n"
"\n"
"}")
        self.tableWidget_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_4.setRowCount(1)
        self.tableWidget_4.setColumnCount(7)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_4.verticalHeader().setStretchLastSection(False)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(320, 630, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_62 = QtWidgets.QLabel(self.tab_4)
        self.label_62.setGeometry(QtCore.QRect(20, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_4)
        self.label_63.setGeometry(QtCore.QRect(20, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_63.setObjectName("label_63")
        self.textEdit_39 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_39.setEnabled(False)
        self.textEdit_39.setGeometry(QtCore.QRect(20, 30, 270, 50))
        self.textEdit_39.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_39.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_39.setLineWidth(1)
        self.textEdit_39.setObjectName("textEdit_39")
        self.textEdit_40 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_40.setGeometry(QtCore.QRect(20, 590, 270, 90))
        self.textEdit_40.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit_40.setObjectName("textEdit_40")
        self.label_64 = QtWidgets.QLabel(self.tab_4)
        self.label_64.setGeometry(QtCore.QRect(20, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_4)
        self.label_65.setGeometry(QtCore.QRect(20, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_65.setObjectName("label_65")
        self.textEdit_41 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_41.setEnabled(False)
        self.textEdit_41.setGeometry(QtCore.QRect(20, 270, 270, 50))
        self.textEdit_41.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_41.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_41.setLineWidth(1)
        self.textEdit_41.setObjectName("textEdit_41")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(930, 640, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_66 = QtWidgets.QLabel(self.tab_4)
        self.label_66.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_66.setObjectName("label_66")
        self.textEdit_42 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_42.setEnabled(False)
        self.textEdit_42.setGeometry(QtCore.QRect(20, 350, 270, 50))
        self.textEdit_42.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_42.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_42.setLineWidth(1)
        self.textEdit_42.setObjectName("textEdit_42")
        self.textEdit_43 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_43.setEnabled(False)
        self.textEdit_43.setGeometry(QtCore.QRect(20, 430, 130, 50))
        self.textEdit_43.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_43.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_43.setLineWidth(1)
        self.textEdit_43.setObjectName("textEdit_43")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_8.setGeometry(QtCore.QRect(320, 0, 951, 631))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_8.setFont(font)
        self.tableWidget_8.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: rgb(225, 255, 254);\n"
"\n"
"}")
        self.tableWidget_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_8.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_8.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_8.setShowGrid(True)
        self.tableWidget_8.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_8.setRowCount(1)
        self.tableWidget_8.setColumnCount(12)
        self.tableWidget_8.setObjectName("tableWidget_8")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(11, item)
        self.tableWidget_8.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_8.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_8.verticalHeader().setStretchLastSection(False)
        self.label_67 = QtWidgets.QLabel(self.tab_4)
        self.label_67.setGeometry(QtCore.QRect(20, 400, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_67.setObjectName("label_67")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_15.setGeometry(QtCore.QRect(640, 640, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_68 = QtWidgets.QLabel(self.tab_4)
        self.label_68.setGeometry(QtCore.QRect(20, 560, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_68.setObjectName("label_68")
        self.textEdit_44 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_44.setEnabled(False)
        self.textEdit_44.setGeometry(QtCore.QRect(20, 110, 270, 50))
        self.textEdit_44.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_44.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_44.setLineWidth(1)
        self.textEdit_44.setObjectName("textEdit_44")
        self.textEdit_45 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_45.setEnabled(False)
        self.textEdit_45.setGeometry(QtCore.QRect(20, 190, 270, 50))
        self.textEdit_45.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_45.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_45.setLineWidth(1)
        self.textEdit_45.setObjectName("textEdit_45")
        self.textEdit_46 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_46.setEnabled(False)
        self.textEdit_46.setGeometry(QtCore.QRect(160, 430, 130, 50))
        self.textEdit_46.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_46.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_46.setLineWidth(1)
        self.textEdit_46.setObjectName("textEdit_46")
        self.label_69 = QtWidgets.QLabel(self.tab_4)
        self.label_69.setGeometry(QtCore.QRect(160, 400, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.tab_4)
        self.label_70.setGeometry(QtCore.QRect(160, 480, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_70.setObjectName("label_70")
        self.textEdit_47 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_47.setEnabled(False)
        self.textEdit_47.setGeometry(QtCore.QRect(160, 510, 130, 50))
        self.textEdit_47.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_47.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_47.setLineWidth(1)
        self.textEdit_47.setObjectName("textEdit_47")
        self.textEdit_48 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_48.setEnabled(False)
        self.textEdit_48.setGeometry(QtCore.QRect(20, 510, 130, 50))
        self.textEdit_48.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_48.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_48.setLineWidth(1)
        self.textEdit_48.setObjectName("textEdit_48")
        self.label_71 = QtWidgets.QLabel(self.tab_4)
        self.label_71.setGeometry(QtCore.QRect(20, 480, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_71.setObjectName("label_71")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_11.setGeometry(QtCore.QRect(320, 640, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:15pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_4, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 1298, 40))
        self.widget.setStyleSheet("QWidget\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:12px;\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(1050, 10, 250, 30))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/\n"
"    font-weight:bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 150 , 254);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(7, 114, 254);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(14 , 135 , 228);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(17, 17, 230, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(260, 16, 50, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setGeometry(QtCore.QRect(310, 14, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:10pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QDateEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QDateEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.dateEdit.setDisplayFormat("yyyy")
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(490, 15, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("QComboBox\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:10pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QComboBox:focus\n"
"{\n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(420, 16, 70, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        ApprovePanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(ApprovePanel)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApprovePanel)

    def retranslateUi(self, ApprovePanel):
        _translate = QtCore.QCoreApplication.translate
        ApprovePanel.setWindowTitle(_translate("ApprovePanel", "Approvement"))
        self.label_33.setText(_translate("ApprovePanel", "Staff Name"))
        self.label_34.setText(_translate("ApprovePanel", "Staff ID"))
        self.label_35.setText(_translate("ApprovePanel", "First Date of Leave"))
        self.label_36.setText(_translate("ApprovePanel", "Last Date of Leave"))
        self.label_37.setText(_translate("ApprovePanel", "Duration(Day)"))
        self.label_38.setText(_translate("ApprovePanel", "Remarks"))
        self.label_39.setText(_translate("ApprovePanel", "Type of Leave"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("ApprovePanel", "No."))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("ApprovePanel", "Staff Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("ApprovePanel", "Staff ID"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("ApprovePanel", "Type"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("ApprovePanel", "Submitted On"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("ApprovePanel", "Start Date"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("ApprovePanel", "Start Time"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("ApprovePanel", "End Date"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("ApprovePanel", "End Time"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("ApprovePanel", "Duration(Day)"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("ApprovePanel", "Remarks"))
        self.pushButton_2.setText(_translate("ApprovePanel", "ACCEPT"))
        self.pushButton_5.setText(_translate("ApprovePanel", "DECLINE"))
        self.pushButton_7.setText(_translate("ApprovePanel", "ACCEPT ALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ApprovePanel", "Approve For Leave Requests"))
        self.label_24.setText(_translate("ApprovePanel", "Date of OT"))
        self.label_25.setText(_translate("ApprovePanel", "Start From"))
        self.label_26.setText(_translate("ApprovePanel", "Until"))
        self.label_27.setText(_translate("ApprovePanel", "OT Hour(s)"))
        self.label_28.setText(_translate("ApprovePanel", "Remarks"))
        self.pushButton.setText(_translate("ApprovePanel", "ACCEPT"))
        self.label_31.setText(_translate("ApprovePanel", "Staff ID"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ApprovePanel", "No."))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ApprovePanel", "Staff Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ApprovePanel", "Staff ID"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("ApprovePanel", "Submitted On"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("ApprovePanel", "OT Date"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("ApprovePanel", "Start Time"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("ApprovePanel", "Finish Time"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("ApprovePanel", "Duration(h)"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("ApprovePanel", "Remarks"))
        self.pushButton_4.setText(_translate("ApprovePanel", "DECLINE"))
        self.label_32.setText(_translate("ApprovePanel", "Staff Name"))
        self.pushButton_9.setText(_translate("ApprovePanel", "ACCEPT ALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ApprovePanel", "Approve For OT Applications"))
        self.label_40.setText(_translate("ApprovePanel", "Staff Name"))
        self.label_41.setText(_translate("ApprovePanel", "Staff ID"))
        self.label_30.setText(_translate("ApprovePanel", "Date of Late Clock-In"))
        self.pushButton_6.setText(_translate("ApprovePanel", "DECLINE"))
        self.label_42.setText(_translate("ApprovePanel", "Clock-In Time"))
        self.pushButton_3.setText(_translate("ApprovePanel", "ACCEPT"))
        self.label_44.setText(_translate("ApprovePanel", "Remarks"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ApprovePanel", "No."))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ApprovePanel", "Staff Name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("ApprovePanel", "Staff ID"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("ApprovePanel", "Submitted On"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("ApprovePanel", "Date of Late Clock-In"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("ApprovePanel", "Clock-In Time"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("ApprovePanel", "Remarks"))
        self.pushButton_10.setText(_translate("ApprovePanel", "ACCEPT ALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ApprovePanel", "Approve For Late Clock-In Requests"))
        self.label_62.setText(_translate("ApprovePanel", "Staff Name"))
        self.label_63.setText(_translate("ApprovePanel", "Clock Out"))
        self.label_64.setText(_translate("ApprovePanel", "Staff ID"))
        self.label_65.setText(_translate("ApprovePanel", "Clock Date"))
        self.pushButton_14.setText(_translate("ApprovePanel", "DECLINE"))
        self.label_66.setText(_translate("ApprovePanel", "Clock In"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("ApprovePanel", "No."))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("ApprovePanel", "Staff Name"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("ApprovePanel", "Staff ID"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("ApprovePanel", "Submitted On"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("ApprovePanel", "Clock Date"))
        item = self.tableWidget_8.horizontalHeaderItem(5)
        item.setText(_translate("ApprovePanel", "Clock In"))
        item = self.tableWidget_8.horizontalHeaderItem(6)
        item.setText(_translate("ApprovePanel", "Clock Out"))
        item = self.tableWidget_8.horizontalHeaderItem(7)
        item.setText(_translate("ApprovePanel", "Out-1"))
        item = self.tableWidget_8.horizontalHeaderItem(8)
        item.setText(_translate("ApprovePanel", "In-1"))
        item = self.tableWidget_8.horizontalHeaderItem(9)
        item.setText(_translate("ApprovePanel", "Out-2"))
        item = self.tableWidget_8.horizontalHeaderItem(10)
        item.setText(_translate("ApprovePanel", "In-2"))
        item = self.tableWidget_8.horizontalHeaderItem(11)
        item.setText(_translate("ApprovePanel", "Remarks"))
        self.label_67.setText(_translate("ApprovePanel", "Out-1"))
        self.pushButton_15.setText(_translate("ApprovePanel", "ACCEPT"))
        self.label_68.setText(_translate("ApprovePanel", "Remarks"))
        self.label_69.setText(_translate("ApprovePanel", "In-1"))
        self.label_70.setText(_translate("ApprovePanel", "In-2"))
        self.label_71.setText(_translate("ApprovePanel", "Out-2"))
        self.pushButton_11.setText(_translate("ApprovePanel", "ACCEPT ALL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ApprovePanel", "Approve For Time Record Applications"))
        self.pushButton_8.setText(_translate("ApprovePanel", "Return To Main Window"))
        self.checkBox.setText(_translate("ApprovePanel", "History Review Mode"))
        self.label.setText(_translate("ApprovePanel", "Year"))
        self.comboBox_3.setCurrentText(_translate("ApprovePanel", "01"))
        self.comboBox_3.setItemText(0, _translate("ApprovePanel", "01"))
        self.comboBox_3.setItemText(1, _translate("ApprovePanel", "02"))
        self.comboBox_3.setItemText(2, _translate("ApprovePanel", "03"))
        self.comboBox_3.setItemText(3, _translate("ApprovePanel", "04"))
        self.comboBox_3.setItemText(4, _translate("ApprovePanel", "05"))
        self.comboBox_3.setItemText(5, _translate("ApprovePanel", "06"))
        self.comboBox_3.setItemText(6, _translate("ApprovePanel", "07"))
        self.comboBox_3.setItemText(7, _translate("ApprovePanel", "08"))
        self.comboBox_3.setItemText(8, _translate("ApprovePanel", "09"))
        self.comboBox_3.setItemText(9, _translate("ApprovePanel", "10"))
        self.comboBox_3.setItemText(10, _translate("ApprovePanel", "11"))
        self.comboBox_3.setItemText(11, _translate("ApprovePanel", "12"))
        self.comboBox_3.setItemText(12, _translate("ApprovePanel", "All"))
        self.label_2.setText(_translate("ApprovePanel", "Month"))
