# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgetrecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgetRecord(object):
    def setupUi(self, ForgetRecord):
        ForgetRecord.setObjectName("ForgetRecord")
        ForgetRecord.resize(959, 491)
        ForgetRecord.setMinimumSize(QtCore.QSize(959, 491))
        ForgetRecord.setMaximumSize(QtCore.QSize(959, 491))
        ForgetRecord.setStyleSheet("QDialog\n"
"{\n"
"    background-color: rgb(234, 255, 185)\n"
"}")
        self.pushButton = QtWidgets.QPushButton(ForgetRecord)
        self.pushButton.setGeometry(QtCore.QRect(750, 300, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 199, 1);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(21, 175, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 113, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ForgetRecord)
        self.pushButton_2.setGeometry(QtCore.QRect(750, 360, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(255, 170, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(230, 153, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"    font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(197, 128, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(ForgetRecord)
        self.tableWidget.setGeometry(QtCore.QRect(3, 35, 950, 231))
        self.tableWidget.setStyleSheet("QTableWidget::item:selected {\n"
"    background-color:#C1272D;\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(36, 236, 239))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.dateEdit_3 = QtWidgets.QDateEdit(ForgetRecord)
        self.dateEdit_3.setGeometry(QtCore.QRect(40, 300, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(12)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setStyleSheet("QDateEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QDateEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QDateEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.dateEdit_3.setWrapping(False)
        self.dateEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_3.setDisplayFormat("dd/MM/yyyy")
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.label = QtWidgets.QLabel(ForgetRecord)
        self.label.setGeometry(QtCore.QRect(40, 270, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ForgetRecord)
        self.label_2.setGeometry(QtCore.QRect(40, 330, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ForgetRecord)
        self.label_3.setGeometry(QtCore.QRect(550, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(ForgetRecord)
        self.textEdit.setGeometry(QtCore.QRect(550, 300, 190, 150))
        self.textEdit.setStyleSheet("QTextEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(ForgetRecord)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(200, 0, 0);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(176, 0, 0);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"     font-size:14pt;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(147, 0, 0);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"    font-size:13pt;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.timeEdit_2 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_2.setGeometry(QtCore.QRect(40, 360, 120, 30))
        self.timeEdit_2.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_2.setAccelerated(True)
        self.timeEdit_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_2.setProperty("showGroupSeparator", True)
        self.timeEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_2.setDisplayFormat("hh:mm")
        self.timeEdit_2.setCalendarPopup(True)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(ForgetRecord)
        self.dateEdit.setGeometry(QtCore.QRect(50, 6, 121, 21))
        self.dateEdit.setStyleSheet("QDateEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255,255);\n"
"}\n"
"\n"
"QDateEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QDateEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.dateEdit.setDisplayFormat("yyyy")
        self.dateEdit.setObjectName("dateEdit")
        self.label_29 = QtWidgets.QLabel(ForgetRecord)
        self.label_29.setGeometry(QtCore.QRect(11, 1, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_29.setObjectName("label_29")
        self.comboBox_3 = QtWidgets.QComboBox(ForgetRecord)
        self.comboBox_3.setGeometry(QtCore.QRect(260, 6, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("QComboBox\n"
"\n"
"    {font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:color:rgb(74, 74, 74);\n"
"   font-size:12pt;\n"
"\n"
"}\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_30 = QtWidgets.QLabel(ForgetRecord)
        self.label_30.setGeometry(QtCore.QRect(200, 0, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_30.setObjectName("label_30")
        self.label_4 = QtWidgets.QLabel(ForgetRecord)
        self.label_4.setGeometry(QtCore.QRect(380, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ForgetRecord)
        self.label_5.setGeometry(QtCore.QRect(40, 390, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.timeEdit_3 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_3.setGeometry(QtCore.QRect(40, 420, 120, 30))
        self.timeEdit_3.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_3.setAccelerated(True)
        self.timeEdit_3.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_3.setProperty("showGroupSeparator", True)
        self.timeEdit_3.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_3.setDisplayFormat("hh:mm")
        self.timeEdit_3.setCalendarPopup(True)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_4.setGeometry(QtCore.QRect(230, 300, 120, 30))
        self.timeEdit_4.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_4.setAccelerated(True)
        self.timeEdit_4.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_4.setProperty("showGroupSeparator", True)
        self.timeEdit_4.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_4.setDisplayFormat("hh:mm")
        self.timeEdit_4.setCalendarPopup(True)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.timeEdit_5 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_5.setGeometry(QtCore.QRect(230, 330, 120, 30))
        self.timeEdit_5.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_5.setAccelerated(True)
        self.timeEdit_5.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_5.setProperty("showGroupSeparator", True)
        self.timeEdit_5.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_5.setDisplayFormat("hh:mm")
        self.timeEdit_5.setCalendarPopup(True)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.timeEdit_6 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_6.setGeometry(QtCore.QRect(230, 390, 120, 30))
        self.timeEdit_6.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_6.setAccelerated(True)
        self.timeEdit_6.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_6.setProperty("showGroupSeparator", True)
        self.timeEdit_6.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_6.setDisplayFormat("hh:mm")
        self.timeEdit_6.setCalendarPopup(True)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.timeEdit_7 = QtWidgets.QTimeEdit(ForgetRecord)
        self.timeEdit_7.setGeometry(QtCore.QRect(230, 420, 120, 30))
        self.timeEdit_7.setStyleSheet("QTimeEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(77,77,77);\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QTimeEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QTimeEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.timeEdit_7.setAccelerated(True)
        self.timeEdit_7.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.timeEdit_7.setProperty("showGroupSeparator", True)
        self.timeEdit_7.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 3), QtCore.QTime(0, 0, 0)))
        self.timeEdit_7.setDisplayFormat("hh:mm")
        self.timeEdit_7.setCalendarPopup(True)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.label_6 = QtWidgets.QLabel(ForgetRecord)
        self.label_6.setGeometry(QtCore.QRect(180, 300, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(ForgetRecord)
        self.label_7.setGeometry(QtCore.QRect(180, 330, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ForgetRecord)
        self.label_8.setGeometry(QtCore.QRect(180, 390, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(ForgetRecord)
        self.label_9.setGeometry(QtCore.QRect(180, 420, 50, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.checkBox = QtWidgets.QCheckBox(ForgetRecord)
        self.checkBox.setGeometry(QtCore.QRect(180, 280, 131, 17))
        self.checkBox.setStyleSheet("QCheckBox\n"
"{\n"
"    font-size:9pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.label_31 = QtWidgets.QLabel(ForgetRecord)
        self.label_31.setGeometry(QtCore.QRect(40, 450, 270, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(229, 0, 0)\n"
"}")
        self.label_31.setObjectName("label_31")
        self.checkBox_2 = QtWidgets.QCheckBox(ForgetRecord)
        self.checkBox_2.setGeometry(QtCore.QRect(180, 370, 131, 17))
        self.checkBox_2.setStyleSheet("QCheckBox\n"
"{\n"
"    font-size:9pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(ForgetRecord)
        self.checkBox_3.setGeometry(QtCore.QRect(18, 336, 31, 17))
        self.checkBox_3.setStyleSheet("QCheckBox\n"
"{\n"
"    font-size:9pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.checkBox_3.setText("")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(ForgetRecord)
        self.checkBox_4.setGeometry(QtCore.QRect(18, 397, 21, 17))
        self.checkBox_4.setStyleSheet("QCheckBox\n"
"{\n"
"    font-size:9pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.checkBox_4.setText("")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_11 = QtWidgets.QLabel(ForgetRecord)
        self.label_11.setGeometry(QtCore.QRect(380, 370, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.textEdit_3 = QtWidgets.QTextEdit(ForgetRecord)
        self.textEdit_3.setGeometry(QtCore.QRect(380, 300, 150, 31))
        self.textEdit_3.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:10pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_3.setLineWidth(1)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_10 = QtWidgets.QLabel(ForgetRecord)
        self.label_10.setGeometry(QtCore.QRect(380, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel\n"
"{\n"
"    font-size:11pt;\n"
"    color:rgb(111,111,111);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.textEdit_4 = QtWidgets.QTextEdit(ForgetRecord)
        self.textEdit_4.setGeometry(QtCore.QRect(380, 400, 150, 31))
        self.textEdit_4.setStyleSheet("QTextEdit\n"
"\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(50, 50, 50);\n"
"   font-size:10pt;\n"
"    background-color:rgb(255, 251, 201);\n"
"}\n"
"")
        self.textEdit_4.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_4.setLineWidth(1)
        self.textEdit_4.setObjectName("textEdit_4")

        self.retranslateUi(ForgetRecord)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ForgetRecord)

    def retranslateUi(self, ForgetRecord):
        _translate = QtCore.QCoreApplication.translate
        ForgetRecord.setWindowTitle(_translate("ForgetRecord", "Forget Record Time"))
        self.pushButton.setText(_translate("ForgetRecord", "Send"))
        self.pushButton_2.setText(_translate("ForgetRecord", "Withdraw"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ForgetRecord", "Request ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ForgetRecord", "Request DTTM"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ForgetRecord", "Clock Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ForgetRecord", "Clock-In"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ForgetRecord", "Clock-Out"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ForgetRecord", "Out-1"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ForgetRecord", "In-1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ForgetRecord", "Out-2"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ForgetRecord", "In-2"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ForgetRecord", "Remarks"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ForgetRecord", "Leader"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ForgetRecord", "DM"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ForgetRecord", "HR"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("ForgetRecord", "Date"))
        self.label_2.setText(_translate("ForgetRecord", "Clock-In Time"))
        self.label_3.setText(_translate("ForgetRecord", "Remarks (Optional)"))
        self.pushButton_3.setText(_translate("ForgetRecord", "Close"))
        self.label_29.setText(_translate("ForgetRecord", "Year"))
        self.comboBox_3.setCurrentText(_translate("ForgetRecord", "01"))
        self.comboBox_3.setItemText(0, _translate("ForgetRecord", "01"))
        self.comboBox_3.setItemText(1, _translate("ForgetRecord", "02"))
        self.comboBox_3.setItemText(2, _translate("ForgetRecord", "03"))
        self.comboBox_3.setItemText(3, _translate("ForgetRecord", "04"))
        self.comboBox_3.setItemText(4, _translate("ForgetRecord", "05"))
        self.comboBox_3.setItemText(5, _translate("ForgetRecord", "06"))
        self.comboBox_3.setItemText(6, _translate("ForgetRecord", "07"))
        self.comboBox_3.setItemText(7, _translate("ForgetRecord", "08"))
        self.comboBox_3.setItemText(8, _translate("ForgetRecord", "09"))
        self.comboBox_3.setItemText(9, _translate("ForgetRecord", "10"))
        self.comboBox_3.setItemText(10, _translate("ForgetRecord", "11"))
        self.comboBox_3.setItemText(11, _translate("ForgetRecord", "12"))
        self.comboBox_3.setItemText(12, _translate("ForgetRecord", "All"))
        self.label_30.setText(_translate("ForgetRecord", "Month"))
        self.label_4.setText(_translate("ForgetRecord", "(Year & Month of Clock-In Forgotten)"))
        self.label_5.setText(_translate("ForgetRecord", "Clock-Out Time"))
        self.label_6.setText(_translate("ForgetRecord", "Out-1"))
        self.label_7.setText(_translate("ForgetRecord", "In-1"))
        self.label_8.setText(_translate("ForgetRecord", "Out-2"))
        self.label_9.setText(_translate("ForgetRecord", "In-2"))
        self.checkBox.setText(_translate("ForgetRecord", "Enable In-1/Out-1"))
        self.label_31.setText(_translate("ForgetRecord", "Please input the correct time range!"))
        self.checkBox_2.setText(_translate("ForgetRecord", "Enable In-2/Out-2"))
        self.label_11.setText(_translate("ForgetRecord", "OT Time"))
        self.label_10.setText(_translate("ForgetRecord", "Work Time"))
