# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminMain(object):
    def setupUi(self, AdminMain):
        AdminMain.setObjectName("AdminMain")
        AdminMain.resize(900, 546)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdminMain.sizePolicy().hasHeightForWidth())
        AdminMain.setSizePolicy(sizePolicy)
        AdminMain.setMinimumSize(QtCore.QSize(900, 200))
        AdminMain.setMaximumSize(QtCore.QSize(900, 600))
        AdminMain.setStyleSheet("QMainWindow\n"
"{\n"
"\n"
"    background-color:rgb(255, 255, 253);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AdminMain)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 70, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font-size:18pt;\n"
"    color:white;\n"
"    background-color:rgb(0, 0, 182);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px; \n"
"    padding-top:-3px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(0, 0, 188);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 160, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font-size:18pt;\n"
"    color:white;\n"
"    background-color:rgb(0, 0, 182);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px; \n"
"    padding-top:-3px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(0, 0, 188);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 250, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font-size:18pt;\n"
"    color:white;\n"
"    background-color:rgb(0, 0, 182);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px; \n"
"    padding-top:-3px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(0, 0, 188);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 340, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font-size:18pt;\n"
"    color:white;\n"
"    background-color:rgb(0, 0, 182);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px; \n"
"    padding-top:-3px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(0, 0, 188);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -10, 901, 41))
        self.widget.setStyleSheet("QWidget\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:18pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 182);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:12px;\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(760, 10, 140, 30))
        self.pushButton_7.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/\n"
"    font-weight:bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 182);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 188);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:13pt;\n"
"    /*字体颜色为白色*/\n"
"    font-weight:bold;    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 182);\n"
"    /*边框圆角半径为8像素*/ \n"
"\n"
"}\n"
"\n"
"QLabel:hover\n"
"{\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QLabel:pressed\n"
"{\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(490, 70, 350, 361))
        self.widget_2.setStyleSheet("background-image: url(:/source/1.png);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(60, 430, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font-size:18pt;\n"
"    color:white;\n"
"    background-color:rgb(0, 0, 182);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(0, 0, 127);\n"
"    padding-left:-3px; \n"
"    padding-top:-3px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(0, 0, 188);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 520, 901, 41))
        self.widget_3.setStyleSheet("QWidget\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:18pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(0, 0, 182);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:12px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        AdminMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminMain)
        QtCore.QMetaObject.connectSlotsByName(AdminMain)

    def retranslateUi(self, AdminMain):
        _translate = QtCore.QCoreApplication.translate
        AdminMain.setWindowTitle(_translate("AdminMain", "Administration Mode"))
        self.pushButton.setText(_translate("AdminMain", "Staff Management"))
        self.pushButton_2.setText(_translate("AdminMain", "Team Structure"))
        self.pushButton_3.setText(_translate("AdminMain", "Staff Accounts"))
        self.pushButton_4.setText(_translate("AdminMain", "Export Monthly Data"))
        self.pushButton_7.setText(_translate("AdminMain", "Resume"))
        self.label.setText(_translate("AdminMain", "Administration Mode"))
        self.pushButton_9.setText(_translate("AdminMain", "Calendar Setting"))
import ui.image1_rc
