# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PassWindow(object):
    def setupUi(self, PassWindow):
        PassWindow.setObjectName("PassWindow")
        PassWindow.resize(400, 300)
        PassWindow.setMinimumSize(QtCore.QSize(400, 300))
        PassWindow.setMaximumSize(QtCore.QSize(400, 300))
        self.label_3 = QtWidgets.QLabel(PassWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 141, 16))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(111, 111, 111);\n"
"   font-size:10pt;\n"
"     \n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(PassWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 30, 320, 40))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("QLineEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:grey;\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(PassWindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 100, 320, 40))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("QLineEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:grey;\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(PassWindow)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 141, 16))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(111, 111, 111);\n"
"   font-size:10pt;\n"
"     \n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(PassWindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 170, 320, 40))
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("QLineEdit\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:grey;\n"
"   font-size:12pt;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}\n"
"\n"
"QLineEdit:focus\n"
"{\n"
"    /*背景颜色*/  \n"
"   background-color:rgb(229, 242, 255);\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(PassWindow)
        self.label_5.setGeometry(QtCore.QRect(40, 147, 191, 20))
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    color:rgb(111, 111, 111);\n"
"   font-size:10pt;\n"
"     \n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(PassWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 240, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:15pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#9e1e24;\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#CD5257;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(PassWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 240, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:15pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#C1272D;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:5px;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#9e1e24;\n"
"    padding-left:-3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:-3px;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#CD5257;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(PassWindow)
        QtCore.QMetaObject.connectSlotsByName(PassWindow)

    def retranslateUi(self, PassWindow):
        _translate = QtCore.QCoreApplication.translate
        PassWindow.setWindowTitle(_translate("PassWindow", "Password Changing"))
        self.label_3.setText(_translate("PassWindow", "Old password"))
        self.label_4.setText(_translate("PassWindow", "New password"))
        self.label_5.setText(_translate("PassWindow", "Confirm password again"))
        self.pushButton_2.setText(_translate("PassWindow", "OK"))
        self.pushButton_3.setText(_translate("PassWindow", "Resume"))
